//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialPlus.Server.WebRoleCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialPlus.Server.WebRoleCommon.ResponseStrings", typeof(ResponseStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token cannot be null.
        /// </summary>
        public static string AccessTokenNull {
            get {
                return ResourceManager.GetString("AccessTokenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App key is invalid.
        /// </summary>
        public static string AppKeyInvalid {
            get {
                return ResourceManager.GetString("AppKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App key is missing.
        /// </summary>
        public static string AppKeyMissing {
            get {
                return ResourceManager.GetString("AppKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App unauthorized to perform this action.
        /// </summary>
        public static string AppUnauthorized {
            get {
                return ResourceManager.GetString("AppUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob not found.
        /// </summary>
        public static string BlobNotFound {
            get {
                return ResourceManager.GetString("BlobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob request is null.
        /// </summary>
        public static string BlobRequestNull {
            get {
                return ResourceManager.GetString("BlobRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob size is too big.
        /// </summary>
        public static string BlobTooBig {
            get {
                return ResourceManager.GetString("BlobTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob size is 0 bytes.
        /// </summary>
        public static string BlobTooSmall {
            get {
                return ResourceManager.GetString("BlobTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name not found.
        /// </summary>
        public static string ClientNameNotFound {
            get {
                return ResourceManager.GetString("ClientNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment not found.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime is not specified as an ISO 8601 string..
        /// </summary>
        public static string DateTimeMalformed {
            get {
                return ResourceManager.GetString("DateTimeMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized request.
        /// </summary>
        public static string GenericUnauthorizedError {
            get {
                return ResourceManager.GetString("GenericUnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity is not valid.
        /// </summary>
        public static string IdentityInvalid {
            get {
                return ResourceManager.GetString("IdentityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider is not valid.
        /// </summary>
        public static string IdentityProviderInvalid {
            get {
                return ResourceManager.GetString("IdentityProviderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType is not an image.
        /// </summary>
        public static string ImageBadType {
            get {
                return ResourceManager.GetString("ImageBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image request is null.
        /// </summary>
        public static string ImageRequestNull {
            get {
                return ResourceManager.GetString("ImageRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size is too big.
        /// </summary>
        public static string ImageTooBig {
            get {
                return ResourceManager.GetString("ImageTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size is 0 bytes.
        /// </summary>
        public static string ImageTooSmall {
            get {
                return ResourceManager.GetString("ImageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists.
        /// </summary>
        public static string ItemExists {
            get {
                return ResourceManager.GetString("ItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unlink account since this is the only linked account for the user.
        /// </summary>
        public static string LinkedAccountAlone {
            get {
                return ResourceManager.GetString("LinkedAccountAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked account already exists.
        /// </summary>
        public static string LinkedAccountExists {
            get {
                return ResourceManager.GetString("LinkedAccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked account not found.
        /// </summary>
        public static string LinkedAccountNotFound {
            get {
                return ResourceManager.GetString("LinkedAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation for linked account is invalid.
        /// </summary>
        public static string LinkedAccountOperationInvalid {
            get {
                return ResourceManager.GetString("LinkedAccountOperationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer item exists.
        /// </summary>
        public static string NewerItemExists {
            get {
                return ResourceManager.GetString("NewerItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not allowed to perform this action.
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not following the topic.
        /// </summary>
        public static string NotFollowingTopic {
            get {
                return ResourceManager.GetString("NotFollowingTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not implemented..
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push registration not found.
        /// </summary>
        public static string PushRegistrationNotFound {
            get {
                return ResourceManager.GetString("PushRegistrationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push registration LastUpdatedTime is too old.
        /// </summary>
        public static string PushRegistrationTimeExpired {
            get {
                return ResourceManager.GetString("PushRegistrationTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push registration LastUpdatedTime is in the future.
        /// </summary>
        public static string PushRegistrationTimeTooNew {
            get {
                return ResourceManager.GetString("PushRegistrationTimeTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string must be no more than 25 characters.
        /// </summary>
        public static string QueryTooBig {
            get {
                return ResourceManager.GetString("QueryTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string must be at least 3 characters.
        /// </summary>
        public static string QueryTooSmall {
            get {
                return ResourceManager.GetString("QueryTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply not found.
        /// </summary>
        public static string ReplyNotFound {
            get {
                return ResourceManager.GetString("ReplyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request token cannot be null for Twitter.
        /// </summary>
        public static string RequestTokenNull {
            get {
                return ResourceManager.GetString("RequestTokenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are not allowed to report their own content or user profile..
        /// </summary>
        public static string SelfReportIsNotAllowed {
            get {
                return ResourceManager.GetString("SelfReportIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session token is invalid.
        /// </summary>
        public static string SessionTokenInvalid {
            get {
                return ResourceManager.GetString("SessionTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is missing.
        /// </summary>
        public static string TokenMissing {
            get {
                return ResourceManager.GetString("TokenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name not found.
        /// </summary>
        public static string TopicNameNotFound {
            get {
                return ResourceManager.GetString("TopicNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic not found.
        /// </summary>
        public static string TopicNotFound {
            get {
                return ResourceManager.GetString("TopicNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile already exists.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User unauthorized to perform this action.
        /// </summary>
        public static string UserUnauthorized {
            get {
                return ResourceManager.GetString("UserUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API version in URL is invalid or malformed..
        /// </summary>
        public static string VersionNumbersMalformed {
            get {
                return ResourceManager.GetString("VersionNumbersMalformed", resourceCulture);
            }
        }
    }
}
