#
# Put-AllTables.ps1
#

function Put-AllTables
{
    <#
    .NOTES
       Name: Put-AllTables.ps1
       Requires: AzCopy v4.0 or higher installed in C:\Program Files (x86)\Microsoft SDKs\azure\AzCopy\AzCopy.exe
    .SYNOPSIS
       Uploads all tables from the local filesystem to an Azure storage account.
    .DESCRIPTION
       This script uses AzCopy to upload all the tables from the specified local directory into an Azure storage account.
       It uses the manifest file generated by AzCopy for each table that was previously downloaded.  You cannot upload a 
       table without the corresponding manifest file.
    .PARAMETER Acct
       Name of the Azure Storage Account.
    .PARAMETER Key
       Key to access the Azure Storage Account.
    .PARAMETER Dir       
       Path to the local directory where the tables will be uploaded from.
    #>

    param (
        [Parameter(
             HelpMessage='Name of the Azure Storage Account.'
        )]
        [string]$Acct,

        [Parameter(
             HelpMessage='Key to access the Azure Storage Account.'
        )]
        [string]$Key,

        [Parameter(
             HelpMessage='Path to the local directory where the tables will be uploaded from.'
        )]
        [string]$Dir
    )

    process
    {
        $azcopy = ${env:programfiles(x86)} + "\Microsoft SDKs\azure\AzCopy\AzCopy.exe"

        $ctx = New-AzureStorageContext -StorageAccountName $Acct -StorageAccountKey $Key

        if ($ctx.StorageAccountName -ne "$Acct") {
             Write-Host "Failed to access storage account $Acct"
             return
        }

        # find all the manifest files in the specified directory
        $matchingFiles = Get-ChildItem $Dir -Filter "*.manifest" | Where-Object { $_.Attributes -ne "Directory" }
        $matchingFiles | ForEach {
            $manifestName = $_.Name
            $tableName = $_.Name.Split('_')[1]
            $destTable = "https://$Acct.table.core.windows.net/$tableName"

            Write-Host "Copying $tableName from $Dir to $destTable"

            & $azcopy /Source:$Dir /Dest:$destTable /DestKey:$Key /Manifest:$manifestName /EntityOperation:InsertOrReplace /Z:$Dir\journal /V:"$Dir\${Name}-export.log"
        }

        Write-Host "Uploads complete"
    }
}

