// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Registry.cs" company="Web Advanced">
// Copyright 2012 Web Advanced (www.webadvanced.com)
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace SocialPlus.Server.DependencyResolution
{
    using System.Web.Http.Filters;

    using SocialPlus.Server.Filters;
    using SocialPlus.Server.WebRoleCommon.DependencyResolution;
    using SocialPlus.Server.WebRoleCommon.Versioning;

    /// <summary>
    /// Registry class
    /// </summary>
    public class Registry : BaseRegistry
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Registry"/> class
        /// </summary>
        /// <param name="serviceVersionInfo">info of version of service</param>
        public Registry(IServiceVersionInfo serviceVersionInfo)
            : base(serviceVersionInfo)
        {
            this.For<IAuthenticationFilter>().Singleton().Use<AuthenticationFilter>();
        }
    }
}